services:
  sttm-server:
    container_name: sttm-server-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    parts:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules
    networks:
      - dev

networks:
  dev: